### ISSUE TITLE
Firebase tokens need verification

### ISSUE THREAD

**Issue by aaron13michael** [OpenMic/api#11]
We need a function to verify and identify who is currently logged in via Firebase. The documentation here https://firebase.google.com/docs/auth/admin/verify-id-tokens outlines the criteria that needs to be met for a token to be considered valid.

**Comment by David-Egan** [comment]
Bump. @aaron13michael @danieldrumma is this complete?

**Comment by danieldrumma** [comment]
Currently being worked on by me @David-Egan
