### ISSUE TITLE
User Search isn't working

### ISSUE THREAD

**Issue by aaron13michael** [OpenMic/api#6]
This url http://127.0.0.1:8000/profiles/?username="anystring"/ will return every user. I've tried multiple things but cannot find a way to filter users returned by username. Please fix and update with url patterns for searching

**Comment by David-Egan** [comment]
My bad I forgot to post the appropriate url patterns needed for the search but I will here and also on the actual user story.  The search parameter is simply 'search' which can be changed and extended to multiple parameters if needed.  
URL: /profiles/?search=<Username>  
Example: http://localhost:8000/profiles/?search=degan
